// Fleet/mcp-diffusion/src/jobs.ts
//
// What: Diffusion job lifecycle manager.
// Does: Creates jobs (builtin or custom workflow), tracks ComfyUI progress via
//       WebSocket events + history polling fallback, saves finished images to
//       disk, persists job metadata to a JSONL log, and emits job updates.
// Touches: ComfyClient, filesystem under config.dataDir.
// Touched by: index.ts (REST routes) and mcp.ts (MCP tools).

import { EventEmitter } from "node:events";
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { DiffusionJob, DiffusionParams } from "@lucidity/shared";
import { ComfyClient, type ComfyImageRef } from "./comfy.js";
import type { DiffusionConfig } from "./config.js";
import {
    buildDefaultWorkflow,
    loadWorkflow,
    resolveParams,
    type ComfyGraph,
} from "./workflows.js";

const HISTORY_POLL_MS = 5_000;
const PERSISTED_JOB_LIMIT = 200;

export class JobManager extends EventEmitter {
    readonly comfy: ComfyClient;
    private jobs = new Map<string, DiffusionJob>();
    /** ComfyUI prompt id -> our job id, for socket event routing. */
    private byPromptId = new Map<string, string>();
    private pollTimer?: NodeJS.Timeout;
    private readonly imagesDir: string;
    private readonly logFile: string;

    constructor(private readonly config: DiffusionConfig) {
        super();
        this.imagesDir = path.join(config.dataDir, "images");
        this.logFile = path.join(config.dataDir, "jobs.jsonl");
        fs.mkdirSync(this.imagesDir, { recursive: true });
        fs.mkdirSync(config.workflowsDir, { recursive: true });
        this.loadPersistedJobs();
        this.comfy = new ComfyClient(config.comfyUrl, {
            onProgress: (promptId, value, max) => this.onProgress(promptId, value, max),
            onExecutionError: (promptId, message) => this.onError(promptId, message),
            onSuccess: (promptId) => void this.finalize(promptId),
            // "executed" also fires per output node; finalize handles both paths
            // idempotently, so acting on it just lowers completion latency.
            onExecuted: (promptId) => void this.finalize(promptId),
        });
    }

    start(): void {
        this.comfy.startSocket();
        // Polling fallback: the WS can drop mid-job on a flaky link; history is truth.
        this.pollTimer = setInterval(() => void this.pollActiveJobs(), HISTORY_POLL_MS);
    }

    stop(): void {
        if (this.pollTimer) clearInterval(this.pollTimer);
        this.comfy.stop();
    }

    list(limit = 50): DiffusionJob[] {
        return [...this.jobs.values()]
            .sort((a, b) => b.createdAt - a.createdAt)
            .slice(0, limit);
    }

    get(id: string): DiffusionJob | undefined {
        return this.jobs.get(id);
    }

    imagePath(filename: string): string | undefined {
        // Filenames are generated by us (job id prefix); reject traversal attempts.
        if (filename.includes("/") || filename.includes("\\") || filename.includes(".."))
            return undefined;
        const full = path.join(this.imagesDir, filename);
        return fs.existsSync(full) ? full : undefined;
    }

    /** Create + submit a job. Returns immediately; progress arrives via events. */
    async create(params: DiffusionParams, source: DiffusionJob["source"]): Promise<DiffusionJob> {
        const resolved = resolveParams(params, this.config.defaultCheckpoint);
        const graph: ComfyGraph = resolved.workflow
            ? loadWorkflow(this.config.workflowsDir, resolved.workflow, resolved)
            : buildDefaultWorkflow(resolved);
        const now = Date.now();
        const job: DiffusionJob = {
            id: randomUUID(),
            status: "queued",
            params: { ...params, seed: resolved.seed },
            images: [],
            source,
            createdAt: now,
            updatedAt: now,
        };
        this.jobs.set(job.id, job);
        try {
            job.comfyPromptId = await this.comfy.submit(graph);
            this.byPromptId.set(job.comfyPromptId, job.id);
            await this.refreshQueuePositions();
        } catch (err) {
            job.status = "failed";
            job.error = err instanceof Error ? err.message : String(err);
        }
        this.touch(job);
        return job;
    }

    /** Wait for a job to reach a terminal state (used by the MCP generate tool). */
    waitForCompletion(jobId: string, timeoutMs: number): Promise<DiffusionJob> {
        const existing = this.jobs.get(jobId);
        if (!existing) return Promise.reject(new Error(`Unknown job ${jobId}`));
        if (isTerminal(existing)) return Promise.resolve(existing);
        return new Promise((resolve, reject) => {
            const onJob = (job: DiffusionJob) => {
                if (job.id !== jobId || !isTerminal(job)) return;
                cleanup();
                resolve(job);
            };
            const timer = setTimeout(() => {
                cleanup();
                reject(new Error(`Timed out after ${timeoutMs}ms waiting for job ${jobId}`));
            }, timeoutMs);
            const cleanup = () => {
                clearTimeout(timer);
                this.off("job", onJob);
            };
            this.on("job", onJob);
        });
    }

    async cancel(jobId: string): Promise<DiffusionJob | undefined> {
        const job = this.jobs.get(jobId);
        if (!job || isTerminal(job)) return job;
        if (job.comfyPromptId) {
            const queue = await this.comfy.queue().catch(() => undefined);
            if (queue?.running.includes(job.comfyPromptId)) {
                await this.comfy.interrupt().catch(() => undefined);
            } else {
                await this.comfy.deletePending(job.comfyPromptId).catch(() => undefined);
            }
        }
        job.status = "canceled";
        this.touch(job);
        return job;
    }

    /** Liveness probe for /api/health and the orchestrator's fleet monitor. */
    async comfyOnline(): Promise<boolean> {
        try {
            await this.comfy.systemStats();
            return true;
        } catch {
            return false;
        }
    }

    // ---- internal event plumbing -------------------------------------------

    private jobForPrompt(promptId: string | undefined): DiffusionJob | undefined {
        if (!promptId) return undefined;
        const jobId = this.byPromptId.get(promptId);
        return jobId ? this.jobs.get(jobId) : undefined;
    }

    private onProgress(promptId: string | undefined, value: number, max: number): void {
        const job = this.jobForPrompt(promptId);
        if (!job || isTerminal(job)) return;
        job.status = "running";
        job.queuePosition = undefined;
        job.progress = { value, max };
        this.touch(job);
    }

    private onError(promptId: string, message: string): void {
        const job = this.jobForPrompt(promptId);
        if (!job || isTerminal(job)) return;
        job.status = "failed";
        job.error = message;
        this.touch(job);
    }

    /** Pull final outputs from history, download images, mark completed. */
    private async finalize(promptId: string): Promise<void> {
        const job = this.jobForPrompt(promptId);
        if (!job || isTerminal(job)) return;
        try {
            const history = await this.comfy.history(promptId);
            if (!history) return; // not in history yet; poller will retry
            if (history.error) {
                job.status = "failed";
                job.error = history.error;
            } else if (history.completed) {
                job.images = await this.downloadImages(job, history.images);
                job.status = "completed";
                job.progress = undefined;
            } else {
                return; // still running
            }
            this.touch(job);
        } catch (err) {
            job.status = "failed";
            job.error = err instanceof Error ? err.message : String(err);
            this.touch(job);
        }
    }

    private async downloadImages(
        job: DiffusionJob,
        refs: ComfyImageRef[],
    ): Promise<DiffusionJob["images"]> {
        const saved: DiffusionJob["images"] = [];
        for (const [index, ref] of refs.entries()) {
            const bytes = await this.comfy.fetchImage(ref);
            const ext = path.extname(ref.filename) || ".png";
            const filename = `${job.id}-${index}${ext}`;
            fs.writeFileSync(path.join(this.imagesDir, filename), bytes);
            saved.push({ filename });
        }
        return saved;
    }

    private async pollActiveJobs(): Promise<void> {
        const active = [...this.jobs.values()].filter((j) => !isTerminal(j));
        if (active.length === 0) return;
        await this.refreshQueuePositions().catch(() => undefined);
        for (const job of active) {
            if (job.comfyPromptId) await this.finalize(job.comfyPromptId);
        }
    }

    private async refreshQueuePositions(): Promise<void> {
        const queue = await this.comfy.queue();
        for (const job of this.jobs.values()) {
            if (isTerminal(job) || !job.comfyPromptId) continue;
            if (queue.running.includes(job.comfyPromptId)) {
                if (job.status !== "running") {
                    job.status = "running";
                    job.queuePosition = undefined;
                    this.touch(job);
                }
            } else {
                const idx = queue.pending.indexOf(job.comfyPromptId);
                if (idx >= 0 && job.status === "queued" && job.queuePosition !== idx) {
                    job.queuePosition = idx;
                    this.touch(job);
                }
            }
        }
    }

    private touch(job: DiffusionJob): void {
        job.updatedAt = Date.now();
        if (isTerminal(job)) this.persist(job);
        this.emit("job", { ...job });
    }

    // ---- persistence ---------------------------------------------------------

    /** Append terminal jobs to JSONL so the gallery survives restarts. */
    private persist(job: DiffusionJob): void {
        try {
            fs.appendFileSync(this.logFile, JSON.stringify(job) + "\n");
        } catch {
            /* metadata loss on disk error is acceptable; images are already saved */
        }
    }

    private loadPersistedJobs(): void {
        if (!fs.existsSync(this.logFile)) return;
        const lines = fs.readFileSync(this.logFile, "utf8").split("\n").filter(Boolean);
        for (const line of lines.slice(-PERSISTED_JOB_LIMIT)) {
            try {
                const job = JSON.parse(line) as DiffusionJob;
                this.jobs.set(job.id, job);
            } catch {
                /* skip corrupt line */
            }
        }
    }
}

export function isTerminal(job: DiffusionJob): boolean {
    return job.status === "completed" || job.status === "failed" || job.status === "canceled";
}
